vich_uploader:
    db_driver: orm

    mappings:
       member:
           uri_prefix: /images/member
           upload_destination: '%kernel.project_dir%/public/images/member'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       galerie:
           uri_prefix: /images/galerie
           upload_destination: '%kernel.project_dir%/public/images/galerie'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       
       partner:
           uri_prefix: /images/partner
           upload_destination: '%kernel.project_dir%/public/images/partner'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
       
       social:
           uri_prefix: /images/social
           upload_destination: '%kernel.project_dir%/public/images/social'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true