vich_uploader:
    db_driver: orm

    mappings:
       member:
           uri_prefix: /images/member
           upload_destination: '%kernel.project_dir%/public/images/member'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       galerie:
           uri_prefix: /images/galerie
           upload_destination: '%kernel.project_dir%/public/images/galerie'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
